# Generated by Django 3.0.4 on 2021-10-29 11:21

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.IntegerField(choices=[(11, '和食'), (12, '洋食'), (13, '中華'), (14, 'アジア'), (15, 'カレー'), (16, '焼肉'), (17, '鍋'), (18, '麺類'), (19, '軽食'), (20, 'スイーツ'), (21, '飲食'), (22, 'その他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='public_private',
            field=models.IntegerField(choices=[(11, '公開'), (12, '非公開')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='名前(20文字まで)'),
        ),
    ]
